apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: ""
  volumeName: ebs-static # pv name should be given here
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: persistant-storage
      mountPath: /usr/share/nginx/html 
  volumes:
  - name: persistant-storage
    persistentVolumeClaim:
      claimName: ebs-static-pvc 


