apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: expense
spec:
  containers:
    - name: nginx-container
      image: nginx
    - name: almalinux-container
      image: almalinux:9
      command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']


