apiVersion: v1
kind: Pod
metadata:
  name: label-pod
  labels:
    project: expense
    environment: dev
    component: backend
spec:
  containers:
  - name: label-nginx-container
    image: nginx

  