apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
spec:
  containers:
    - name: resouces-nginx-container
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "120Mi"
          cpu: "250m"
