apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  type: NodePort
  selector: # pod labels
    component: testcomponent
    demo: nodeport
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 30009

---
apiVersion: v1
kind: Pod
metadata:
  name: node-port-pod
  labels:
    component: testcomponent
    demo: nodeport
spec:
  containers:
  - name: nodeportcontainer
    image: nginx






