apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    demo: lb-demo
    environment: dev
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # pod port
    nodePort: 30023
---
apiVersion: v1
kind: Pod
metadata:
  name: lb-pod
  labels:
    demo: lb-demo
    environment: dev
spec:
  containers:
  - name: lb-container
    image: nginx
