apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica-set-1
  # these are replicaset lables
  labels:
     demo: demo-replicasets-1
spec:
  replicas: 3
  # replicaset uses these labels to find the pod for creating desired number of replicas  
  selector:
    matchLabels:
       demo: demo-replicasets
  # pod template
  template:
    metadata:
      labels:
        demo: demo-replicasets
    spec:
      containers:
      - name: replica-nginx-container
        image: nginx:stable-perl

