apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica-set
  # these are replicaset lables
  labels:
     #project: demo-replicasets
     project: pod-replicasets
spec:
  replicas: 3
  # replicaset uses these labels to find the pod for creating desired number of replicas  
  selector:
    matchLabels:
       project: pod-replicasets
  # pod template
  template:
    metadata:
      labels:
        project: pod-replicasets
    spec:
      containers:
      - name: replica-nginx-container
        image: nginx

