apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  #labels of deployment resource
  labels:
    app: frontend
    tier: web
    purpose: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      purpose: deployment-pod
  template:
    metadata:
      labels:
        app: frontend
        purpose: deployment-pod
    spec:
      containers:
      - name: fromtend-dp-container
        image: nginx
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: deployment-lb-service
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    app: frontend
    purpose: deployment-pod
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 30007