# Headless service
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless-service
  labels:
    app: nginx-headless
    demo: statefulset
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None # Headless service will have cluster IP none.
  selector:
    app: nginx
    
---
# Stateful set
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ngnix-statefulset
spec:
  selector:
    matchLabels:
      app: nginx-headless # has to match .spec.template.metadata.labels
      demo: statefulset 
  serviceName: nginx-headless-service
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: nginx-headless # has to match .spec.selector.matchLabels
        demo: statefulset 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.24
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  # Instead of creating a PVC resource, you can directly provide volumeClaim template in statefulset as below
  volumeClaimTemplates: # This is equivalent to pvc
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi