apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  # Labels for deployment resource
  labels:
    project: sample-deployment-project
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      tag: sample-deployment-dev
      env: dev
  template:
    metadata:
      labels:
        tag: sample-deployment-dev
        env: dev
    spec:
     containers:
     - name: sample-deployment-pod
       image: vishnupriyadh/sample-deployment:1.0.0
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sample-deployment-lb
spec:
  type: LoadBalancer
  selector:
    tag: sample-deployment-dev
    env: dev
  ports:
  - protocol: tcp
    port: 80 # service port
    targetPort: 80 # Pod port. even if  you don't give k8s will take it automatically
    nodePort: 30009 # Open this port in any of the phyical server SG. in the inbound rules of SG add this port





