apiVersion: v1
kind: Service
metadata:
  name: demoservice
spec:
  selectors: # pod labels
    component: testcomponent
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
  

---
apiVersion: v1
kind: Pod
metadata:
  name: demopod
  labels:
    component: testcomponent
spec:
  containers:
  - name: democontainer
    image: nginx






